### ISSUE TITLE
Thread safe

### ISSUE THREAD

**Issue by MaximKulikov** [mb3364/java-async-http#9]
It happen if several libs use java-async-http

Exception in thread "pool-3-thread-3" java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:744)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:742)
	at com.mb3364.http.HttpClient.request(HttpClient.java:68)
	at com.mb3364.http.HttpClient.post(HttpClient.java:197)
	at com.mb3364.http.AsyncHttpClient.access$701(AsyncHttpClient.java:12)
	at com.mb3364.http.AsyncHttpClient$8.run(AsyncHttpClient.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MaximKulikov** [comment]
Abadoned
